apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongoexpress
spec:
  selector:
    matchLabels:
      app: my-mongoexpress
  template:
    metadata:
      labels:
        app: my-mongoexpress
    spec:
      containers:
      - name: my-mongoexpress
        image: mongo-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: my-mongodb-secret 
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: my-mongodb-secret
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: databaseurl
